canonical/tls-certificates-requirer-operator

.github/workflows/publish-charm.yaml
.github/workflows/push.yaml

Passes charmcraft token as variable in publish action
Reason: Environment Secrets are not available on Reusable Workflow

Passes charmcraft token as variable in publish action

---

README.md

Fixes the name of the operator in the README:
- Uses the actual registered name of the charm
When deploying the charm using the current names from README it results in the following error:
```
juju deploy tls-requirer-operator
ERROR resolving error: The Charm with the given name was not found in the Store.
```

Fixes the name of the operator in the README

---

src/charm.py
tests/unit/test_charm.py

The `chain` is being json dumped when stored in the juju-secret, this pr does the reverse of that when reading the chain from the secret and calls `json.loads` to get a list instead of one string.

Loads the list of chain certificates from json

---

.github/workflows/integration-test.yaml

The point releases of LXD are not maintained long enough, causing us to constantly update the build. Using 5.0 should prevent this.

Use LXD 5.0 for integration tests

---

lib/charms/tls_certificates_interface/v2/tls_certificates.py
src/charm.py
test-requirements.txt
tests/integration/test_integration.py
tests/unit/test_charm.py
tox.ini

If relation created immediately before CSR generated, RuntimeError happens when we request certificate creation. 
Certificate creation request needs to wait for CSR generation first. Aiming to solve following issue: https://github.com/canonical/tls-certificates-requirer-operator/issues/13
tls_certificate_interface library version is updated to 10.

Certificate creation request needs to wait for CSR generation

---

config.yaml
lib/charms/tls_certificates_interface/v2/tls_certificates.py
src/charm.py
tests/integration/test_integration.py
tests/unit/test_charm.py

Each unit generates its own private key and CSR and receives its own certificate. This makes it possible to scale this charm to an arbitrary number of units.
Fixes #22

feat: Implements per-unit certificate requests

---

src/charm.py
tests/unit/test_charm.py

The operator now generates a csr and requests certificates in all units every time a new unit joins the relation. 
To avoid this behavior we prevent generating a new csr for the unit or requesting a new certificate if those are present for the unit.
With this solution, the operator can't have multiple csrs and certs per unit.

fix: Generates csr and requests cert only if the unit does not have them

---

requirements.txt
src/charm.py
tests/unit/test_charm.py

Uses refresh option in secret.get_content:
Gets the content of the latest revision of the secret

fix: Uses refresh option in secret.get_content

---

config.yaml
src/charm.py
tests/unit/test_charm.py

It was currently not possible to run this charm as a requirer of one of the LEGO charms as a TLS provider because the CSR generated by the tls-certificates requirer had a common name set to be `<app name>-<unit number>.<model name>`. This PR makes the common name configurable, making it possible to get certs from any Let's Encrypt charm provider.

feat: Adds common_name juju config

---

src/charm.py
tests/integration/test_integration.py
tests/unit/test_charm.py

There was a bug where the CA chain was to big to be stored in a Juju secret. As the chain is not used by this charm, we simply remove any behavior storing and retrieving it.
Fixes #38

fix: Does not store ca chain

---

metadata.yaml

Adds link to Charmhub discourse documentation so that this charm's documentation can be managed the same way as the other TLS Certificates charms.

docs: Adds link to Charmhub discourse documentation

---

pyproject.toml
src/charm.py
test-requirements.in
test-requirements.txt
tests/integration/test_integration.py
tests/unit/test_charm.py
tox.ini

In order to standardise with the new default linter for charms and between TLS projects, we are moving the lint checks from  `pflake8` and `isort` to `ruff`. We also take the opportunity to "rebase" the tox.ini and pyproject.toml files onto what's default coming out of `charmcraft init`.

chore: use ruff for linting

---

pyproject.toml
requirements.in
requirements.txt
test-requirements.in
test-requirements.txt
tox.ini

Remove black formatter
As we switched to Ruff, we use it for formatting as well.
- https://github.com/astral-sh/ruff

chore: remove black formatter

---

src/charm.py

It was the case that when the tls provider would send a new cert, we would store it in secrets but we would never actually use it. When running `get-certificate` we would still get the old one.

fix: get latest version of secret

---

tests/integration/test_integration.py

Use tls provider from stable risk, reducing the risk of tests failing because of issues in other charms used in tests.

chore: use self signed cert operator from stable risk

---

.github/dependabot.yml

This reverts commit 253a9c0678875cbd8d8f958d0972604375d2fa61.
The commit was pushed to main by mistake and the protection rules did not catch it. Protection rules are fixed now, commit is reverted here, and a PR with the same change will be created for review.

fix: Revert "Adds dependency groupping and uses weekly schedule in dependabot

---

.gitignore
config.yaml
src/charm.py
tests/integration/certificates.py
tests/integration/test_integration.py
tests/unit/test_charm.py

Add the following optional configuration options which will be used in every generated CSR:
- `organization_name`: Organization name to be used in the certificate. If not set, no organization name will be used.
- `email_address`: Email address to be used in the certificate. If not set, no email address will be used.
- `country_name`: Country name to be used in the certificate. If not set, no country name will be used.
- `state_or_province_name`: State or province name to be used in the certificate. If not set, no state or province name will be used.
- `locality_name`: Locality name to be used in the certificate. If not set, no locality name will be used.

feat: add common csr configuration options

---

config.yaml
src/charm.py
tests/integration/certificates.py
tests/integration/test_integration.py
tests/unit/test_charm.py

Add `sans_dns` configuration option which takes a comma separated list of DNS Subject Alternative Names (SAN's) and inserts those in the certificate signing request (CSR).  If not set, the following value will be used: `<app name>-<unit number>.<model name>`.
Fixes #118

feat: add sans_dns configuration option

---

.github/workflows/publish-charm.yaml

Publish using charming actions 2.5.0-rc which contains the change to make it possible for the action to read metadata from charmcraft.yaml.
This fixes the publishing issue introduced by #122

fix: publish using charming actions 2.5.0-rc

---

charmcraft.yaml
src/charm.py
tests/integration/test_integration.py
tests/unit/test_charm.py

Add support for a new `app` mode which makes it possible for TLS certificates Requirer to manage certificates at the application level. We now support two modes:
- `unit`: Certificate management at the unit level. Each unit manges its own private key and certificate. This is to represent the generic TLS requirer use case (ex. web servers).
- `app`: certificate management at the app level. This is to represent the ingress use case (or TLS constraints) where tls certs are managed at the application level. Only the leader will unit handles certificate management and the secrets are owned by the application. Though at the moment only 1 certificate per app is supported, with this mechanics in place, it will be easy to add support for more. This is a pre-requisite step to addressing the feature …

feat: add per-app certificate management

---

src/charm.py
tests/integration/certificates.py
tests/integration/conftest.py
tests/integration/test_integration.py
tests/unit/test_charm.py
tests/unit/tls.py
tox.ini

Currently, ruff is only configured to check the files for linting errors. This adds ruff formatting to tox checks.
Review notes:
Only tox.ini contains functional changes, the rest are the result of running tox -e format.

style: Format using ruff

---

test-requirements.in
test-requirements.txt
tests/unit/test_charm.py

Here we replace the harness framework with scenario to simplify and standardize unit tests. Every unit test now consists of :
- Setting up the initial state
- Running an event
- Assessing final state
We already followed this model in our unit tests, now the scenario framework provides straps to enforce this approach.
- https://github.com/canonical/ops-scenario

test: use scenario framework

---

charmcraft.yaml
src/charm.py
tests/integration/certificates.py
tests/integration/test_integration.py
tests/unit/test_charm.py

Here we simplify this charm by getting rid of the duplicated methods for both unit and app modes. Doing so, we prepare the field for supporting multiple certificate requests per unit. Many methods now take `certificate_request` as an input. 
We also make it impossible for two units to request certificates for the same common name. If users want to leverage the scaling ability of this charm, they must use the default common name config option which will automatically generate common names based on unit numbers.

refactor: remove unneeded duplication

---

charmcraft.yaml
src/charm.py
tests/integration/certificates.py
tests/integration/test_integration.py
tests/unit/test_charm.py

Here we add the option to request multiple certificates per app (or unit). Depending on the mode selected, the following values will be used for common name:
- **unit**: `cert-<certificate number>.unit-<unit number>.<app name>.<model name>`
- **app**: `cert-<certificate number>.<app name>.<model name>`
Closes #23

feat: support multiple certificate requests

---

charmcraft.yaml
lib/charms/tls_certificates_interface/v4/tls_certificates.py
src/charm.py
tests/integration/certificates.py
tests/integration/test_integration.py

Some TLS providers support providing CA certificates (ex. self-signed-certificates) and here we want to validate this behavior with tls certificates requirer. Having this feature here would permit identifying issues with the TLS library related to providing CA certificates. We add support for requesting CA certificates.
Fixes #171

feat: add support for requesting CA certificate

---

.github/workflows/build.yaml
.github/workflows/integration-test.yaml
.github/workflows/promote.yaml
.github/workflows/publish-charm.yaml
charmcraft.yaml
tests/integration/test_integration.py

Improves the CI to build, publish and test the charm for both architectures `amd64` and `arm64`

feat: Adds workflows to build and publish the charm on arm64

---

.github/workflows/main.yaml

This charm is built for multiple architecture but was not using the publishing workflow for multiple architectures, and was thus failing to publish at all.

fix: Use multiarch publish workflow

---

.github/renovate.json5

Renovate does not seem happy to handle a specific file with a branch ref in its custom URL specifiers. This PR attempts to use a direct URI to the right file.

fix: Use direct URL for renovate preset
